### ISSUE TITLE
os_unfair_lock_lock is being called from AppDelegate

### ISSUE THREAD

**Issue by fampaySiddharth** [SwiftUIX/Coordinator#6]
If I use debug google service plist for Firebase and initialize with it.
Then Merge throws a os_unfair_lock_lock error, sometimes reactor.dispatch also throws this

![Screenshot 2023-05-31 at 5 59 07 PM](https://github.com/SwiftUIX/Coordinator/assets/92845187/a1d0e4e6-f231-4d6f-a9f3-e1dc77fb7516)

**Comment by fampaySiddharth** [comment]
The 'retainSink' is causing the issue. 
```
public func uploadFCMToken() {
    _ = myRepository().uploadFCMToken().retainSink() <- This retain sink
  }
```

**Comment by vmanot** [comment]
This is related to the Merge framework (and also should be fixed with the recent refactor of `PassthroughTask`).
