### ISSUE TITLE
Not able to build - Type '_SwiftUIX_KeyPress' does not conform to protocol 'Equatable'

### ISSUE THREAD

**Issue by garethlloyd1994** [SwiftUIX/Coordinator#8]
I am attempting to using the below to add via spm:
```swift
 .package(url: "https://github.com/SwiftUIX/Coordinator.git", branch:"master"),
```

I am seeing the error which is because the package is being pointed to master branch of SwiftUIX which is failing.

![Screenshot 2023-09-07 at 2 49 01 pm](https://github.com/SwiftUIX/Coordinator/assets/122424426/f1ed7341-f6c6-4a3c-a943-0c480c5a68eb)

**Comment by vmanot** [comment]
@garethlloyd1994 this should be fixed now, thanks for reporting!
